version: '3.0'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    depends_on:
      - db
    build: backend
    ports:
      - "5000:5000"
    restart: always
